"""
Sprint config serialization.

The GUI works with a ``SprintConfig`` (defined in ``config_parser``) and:

* loads from / saves to a JSON file (``configs/<sprint>.json``)
* imports from / exports to the legacy markdown format
  (``sprint_report_config.md``) so the existing CLI tools keep working.
"""

from __future__ import annotations

import json
import sys
from dataclasses import asdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config_parser import (
    ExclusionEntry,
    ExtraTicket,
    LeaveEntry,
    SprintConfig,
    TeamMember,
    parse_config,
)


# ── JSON ────────────────────────────────────────────────────────────────────

def config_to_dict(cfg: SprintConfig) -> dict:
    return {
        "sprint_name": cfg.sprint_name,
        "sprint_duration_weeks": cfg.sprint_duration_weeks,
        "team_members": [asdict(m) for m in cfg.team_members],
        "meeting_days_reserved": cfg.meeting_days_reserved,
        "planned_leaves": [asdict(l) for l in cfg.planned_leaves],
        "other_exclusions": [asdict(e) for e in cfg.other_exclusions],
        "extra_tickets": [asdict(t) for t in cfg.extra_tickets],
        "excluded_tickets": list(cfg.excluded_tickets),
        "report_date": cfg.report_date,
        "show_per_ticket_details": cfg.show_per_ticket_details,
        "show_daily_log_gaps": cfg.show_daily_log_gaps,
    }


def dict_to_config(data: dict) -> SprintConfig:
    cfg = SprintConfig()
    cfg.sprint_name = data.get("sprint_name", "") or ""
    cfg.sprint_duration_weeks = int(data.get("sprint_duration_weeks", 2) or 2)
    cfg.meeting_days_reserved = float(data.get("meeting_days_reserved", 1.0) or 0.0)
    cfg.report_date = data.get("report_date", "") or ""
    cfg.show_per_ticket_details = bool(data.get("show_per_ticket_details", True))
    cfg.show_daily_log_gaps = bool(data.get("show_daily_log_gaps", True))

    cfg.team_members = [
        TeamMember(
            name=m.get("name", "").strip(),
            role=m.get("role", "").strip(),
            included=bool(m.get("included", True)),
        )
        for m in (data.get("team_members") or [])
        if m.get("name", "").strip()
    ]
    cfg.planned_leaves = [
        LeaveEntry(
            name=l.get("name", "").strip(),
            days=float(l.get("days", 0) or 0),
            notes=l.get("notes", "") or "",
        )
        for l in (data.get("planned_leaves") or [])
        if l.get("name", "").strip()
    ]
    cfg.other_exclusions = [
        ExclusionEntry(
            name=e.get("name", "").strip(),
            hours=float(e.get("hours", 0) or 0),
            reason=e.get("reason", "") or "",
        )
        for e in (data.get("other_exclusions") or [])
        if e.get("name", "").strip()
    ]
    cfg.extra_tickets = [
        ExtraTicket(
            key=t.get("key", "").strip(),
            assignee=t.get("assignee", "") or "",
            notes=t.get("notes", "") or "",
        )
        for t in (data.get("extra_tickets") or [])
        if t.get("key", "").strip()
    ]
    cfg.excluded_tickets = [
        str(k).strip() for k in (data.get("excluded_tickets") or []) if str(k).strip()
    ]
    return cfg


def save_json(cfg: SprintConfig, path: Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(config_to_dict(cfg), indent=2), encoding="utf-8")


def load_json(path: Path) -> SprintConfig:
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    return dict_to_config(data)


# ── Markdown export (subset of fields the parser knows about) ──────────────

_MD_HEADER = """# Sprint Report Configuration

Generated by Sprint Report GUI. The fields below are consumed by
`sprint_report.py` / `fetch_sprint_data.py`.

---

"""


def _bool_to_md(value: bool) -> str:
    return "Yes" if value else "No"


def config_to_markdown(cfg: SprintConfig) -> str:
    out: list[str] = [_MD_HEADER.rstrip(), ""]

    out += [
        "## Sprint Details",
        "",
        f"- **Sprint Name**: `{cfg.sprint_name}`",
        f"- **Sprint Duration (weeks)**: `{cfg.sprint_duration_weeks}`",
        "",
        "---",
        "",
    ]

    out += ["## Team Members", "", "| # | Name | Role | Include in Report |", "| - | ---- | ---- | ----------------- |"]
    for i, m in enumerate(cfg.team_members, 1):
        out.append(f"| {i} | {m.name} | {m.role} | {_bool_to_md(m.included)} |")
    if not cfg.team_members:
        out.append("|   |      |      |                   |")
    out += ["", "---", ""]

    out += [
        "## Capacity Adjustments",
        "",
        "### Time Reserved for Meetings/Ceremonies (per person per sprint)",
        "",
        f"- **Days reserved**: `{cfg.meeting_days_reserved:g}`",
        "",
        "### Planned Leaves",
        "",
        "| Name | Leave Days | Notes |",
        "| ---- | ---------- | ----- |",
    ]
    for l in cfg.planned_leaves:
        out.append(f"| {l.name} | {l.days:g} | {l.notes} |")
    if not cfg.planned_leaves:
        out.append("|      |            |       |")
    out += ["", "### Other Non-Development Activities (per person)", "",
            "| Name | Hours Excluded | Reason |", "| ---- | -------------- | ------ |"]
    for e in cfg.other_exclusions:
        out.append(f"| {e.name} | {e.hours:g} | {e.reason} |")
    if not cfg.other_exclusions:
        out.append("|      |                |        |")
    out += ["", "---", ""]

    out += ["## Extra Tickets", "", "| Ticket Key | Assignee | Notes |",
            "| ---------- | -------- | ----- |"]
    for t in cfg.extra_tickets:
        out.append(f"| {t.key} | {t.assignee} | {t.notes} |")
    if not cfg.extra_tickets:
        out.append("|            |          |       |")
    out += ["", "---", ""]

    out += ["## Tickets to Exclude", "", "| Ticket Key | Reason |",
            "| ---------- | ------ |"]
    for k in cfg.excluded_tickets:
        out.append(f"| {k} |  |")
    if not cfg.excluded_tickets:
        out.append("|            |        |")
    out += ["", "---", ""]

    out += [
        "## Report Options",
        "",
        f"- **Report Date** (calculate logged work up to this date, leave blank for today): `{cfg.report_date}`",
        f"- **Show per-ticket worklog details**: `{_bool_to_md(cfg.show_per_ticket_details)}`",
        f"- **Show daily log gaps** (flag people who haven't logged work on a given day): `{_bool_to_md(cfg.show_daily_log_gaps)}`",
        "",
    ]

    return "\n".join(out) + "\n"


def save_markdown(cfg: SprintConfig, path: Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(config_to_markdown(cfg), encoding="utf-8")


def load_markdown(path: Path) -> SprintConfig:
    return parse_config(path)
